# Generated by Django 5.1 on 2024-08-31 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_genero_peliculas_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='raiting',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
