# Generated by Django 5.1 on 2024-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_peliculas_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
