# Generated by Django 5.1 on 2024-09-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_director_biografia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='peliculas',
            options={'verbose_name': 'Pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
        migrations.RenameField(
            model_name='director',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='director_origen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas_director', to='peliculas.director', verbose_name='Director'),
        ),
    ]
