# Generated by Django 5.1 on 2024-09-13 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_alter_director_options_alter_peliculas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='raiting',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
