# Generated by Django 5.1 on 2024-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_peliculas_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Premium',
                'verbose_name_plural': 'Planes Premium',
            },
        ),
        migrations.AlterField(
            model_name='director',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
