# Generated by Django 5.1 on 2024-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_premium_alter_director_biografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_peliculas/', verbose_name='Imagen'),
        ),
    ]
