# Generated by Django 5.1 on 2024-09-14 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0008_premium_alter_director_biografia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariopremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_premium', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Premium',
                'verbose_name_plural': 'Usuarios Premium',
            },
        ),
        migrations.CreateModel(
            name='AccesoPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_fin', models.DateTimeField(editable=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peliculas.premium')),
                ('usuario_premium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accesos_premium', to='usuariopremium.usuariopremium')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
